
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";



 
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const  GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const  GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const  GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const  GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const  GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const  GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

 
 

export const CLEAR_ERRORS = "CLEAR_ERRORS"